### ISSUE TITLE
serialize in HttpContext dont exists after migration from v6

### ISSUE THREAD

**Issue by evdevru** [adonisjs/adonis-framework#5060]
### Package version

7

### Describe the bug

Property 'serialize' does not exist on type 'HttpContext'
After migration from adonisjs v6

`{
  "version": "0.0.0",
  "private": true,
  "type": "module",
  "license": "UNLICENSED",
  "scripts": {
    "start": "node bin/server.js",
    "build": "node ace build",
    "dev": "node ace serve --hmr",
    "test": "node ace test",
    "lint": "eslint . --fix",
    "format": "prettier --write .",
    "typecheck": "tsc --noEmit"
  },
  "imports": {
    "#generated/*": "./.adonisjs/server/*.js",
    "#transformers/*": "./app/transformers/*.js",
    "#controllers/*": "./app/controllers/*.js",
    "#exceptions/*": "./app/exceptions/*.js",
    "#models/*": "./app/models/*.js",
    "#mails/*": "./app/mails/*.js",
    "#services/*": "./app/services/*.js",
    "#listeners/*": "./app/listeners/*.js",
    "#events/*": "./app/events/*.js",
    "#middleware/*": "./app/middleware/*.js",
    "#validators/*": "./app/validators/*.js",
    "#providers/*": "./providers/*.js",
    "#policies/*": "./app/policies/*.js",
    "#abilities/*": "./app/abilities/*.js",
    "#database/*": "./database/*.js",
    "#start/*": "./start/*.js",
    "#tests/*": "./tests/*.js",
    "#config/*": "./config/*.js",
    "#utils/*": "./utils/*.js",
    "#integrations/*": "./integrations/*.js",
    "#jobs/*": "./app/jobs/*.js",
    "#types/*": "./types/*.js"
  },
  "devDependencies": {
    "@adonisjs/assembler": "^8.0.0",
    "@adonisjs/eslint-config": "^3.0.0",
    "@adonisjs/prettier-config": "^1.4.5",
    "@adonisjs/tsconfig": "^2.0.0",
    "@japa/api-client": "^3.2.1",
    "@japa/assert": "^4.2.0",
    "@japa/plugin-adonisjs": "^5.1.0",
    "@japa/runner": "^4.5.0",
    "@poppinss/ts-exec": "^1.4.4",
    "@types/jsonwebtoken": "^9.0.10",
    "@types/lodash-es": "^4.17.12",
    "@types/luxon": "^3.7.1",
    "@types/node": "^22.19.13",
    "@types/openid": "^2.0.5",
    "@types/slug": "^5.0.9",
    "eslint": "^9.39.3",
    "hot-hook": "^0.4.0",
    "pino-pretty": "^13.1.3",
    "prettier": "^3.8.1",
    "typescript": "~5.8.3",
    "youch": "^4.1.0"
  },
  "dependencies": {
    "@adonisjs/ally": "^6.0.0",
    "@adonisjs/auth": "^10.0.0",
    "@adonisjs/cache": "^2.0.1",
    "@adonisjs/core": "^7.0.1",
    "@adonisjs/cors": "^3.0.0",
    "@adonisjs/drive": "4.0.0-next.1",
    "@adonisjs/lock": "^2.1.0",
    "@adonisjs/lucid": "^22.0.0",
    "@adonisjs/redis": "^10.0.0",
    "@rlanz/bull-queue": "^3.1.0",
    "@vinejs/vine": "^4.3.0",
    "axios": "^1.13.6",
    "jsonwebtoken": "^9.0.3",
    "lodash-es": "^4.17.23",
    "luxon": "^3.7.2",
    "openid": "^2.0.14",
    "pg": "^8.19.0",
    "reflect-metadata": "^0.2.2",
    "slug": "^11.0.1",
    "uuid": "^13.0.0"
  },
  "hotHook": {
    "boundaries": [
      "./app/controllers/**/*.ts",
      "./app/middleware/*.ts"
    ]
  },
  "prettier": "@adonisjs/prettier-config"
}
`

**Comment by evdevru** [comment]
Basic migration guide dont have info about api_provider
Solved by make it

**Comment by xelandr3** [comment]
Hi, I have the same issue after migrating from AdonisJS v6 to v7.

Could you explain what you meant by **“Solved by make it”** and how you configured the **api_provider**?
I’m currently getting the error:

`Property 'serialize' does not exist on type 'HttpContext'`.

If possible, could you share:

* where the provider should be registered
* an example configuration or code snippet

Thanks.

**Comment by xelandr3** [comment]
After digging a bit, I found that adding the api_provider fixes the issue.
For reference, I’m considering adding the same implementation used in the AdonisJS starter kit:

https://github.com/adonisjs/starter-kits/blob/main/api/providers/api_provider.ts

It would be really nice to include something like this in the project or mention it in the migration guide, since the serialize method depends on it and it’s easy to miss during a v6 → v7 migration.

**Comment by AshlinR** [comment]
Solution:

Move the providers directory out of /app to root ./
Copy the provider "api_provider.ts" file from starter kit into the providers dir.
Register the provider in the adonisrc file.  () => import('#providers/api_provider'),
